#!/usr/bin/env tsx
/**
 * Pull every item from RRR's Zoho Books org and write a typed local mirror to
 * packages/service-catalog/src/catalog.generated.ts.
 *
 * Idempotent — safe to re-run any time. Output is committed to git so the
 * repo carries a snapshot of the canonical catalog without requiring the dev
 * to have Zoho credentials handy.
 *
 *   pnpm sync:catalog
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type CatalogItem, deriveCatalogItem, type RawZohoItem } from '@rrr/service-catalog';
import { createZohoClient, type ZohoConfig, type ZohoRegion } from '@rrr/zoho-tools';

const __dirname = dirname(fileURLToPath(import.meta.url));
const envPath = resolve(__dirname, '..', 'apps', 'api', '.env.local');
const outPath = resolve(
  __dirname,
  '..',
  'packages',
  'service-catalog',
  'src',
  'catalog.generated.ts',
);

const env = readFileSync(envPath, 'utf8');
const envGet = (key: string): string =>
  env.match(new RegExp(`^${key}=(.*)$`, 'm'))?.[1]?.trim() ?? '';

const config: ZohoConfig = {
  refreshToken: envGet('ZOHO_REFRESH_TOKEN'),
  clientId: envGet('ZOHO_CLIENT_ID'),
  clientSecret: envGet('ZOHO_CLIENT_SECRET'),
  orgId: envGet('ZOHO_ORG_ID'),
  region: (envGet('ZOHO_REGION') || 'com') as ZohoRegion,
};

for (const [k, v] of Object.entries(config)) {
  if (!v) {
    console.error(`Missing ${k} in ${envPath}`);
    process.exit(2);
  }
}

const client = createZohoClient(config);
console.info('Pulling items from Zoho…');
const rawItems = await client.listAllItems();
console.info(`Got ${rawItems.length} items.`);

// Sort by name first so collision-suffixing is deterministic across runs.
const sortedRaw = [...rawItems].sort((a, b) => String(a.name).localeCompare(String(b.name)));
const idCounts = new Map<string, number>();
const derived: CatalogItem[] = [];
for (const raw of sortedRaw) {
  const item = deriveCatalogItem(raw as unknown as RawZohoItem);
  const baseId = item.id;
  const seen = idCounts.get(baseId) ?? 0;
  if (seen > 0) {
    item.id = `${baseId}_${seen + 1}`;
  }
  idCounts.set(baseId, seen + 1);
  derived.push(item);
}
derived.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

const banner = [
  '// AUTO-GENERATED by scripts/sync-zoho-catalog.ts. Do not edit by hand.',
  `// Last sync: ${new Date().toISOString()}`,
  `// Source org: ${config.orgId}`,
  `// Item count: ${derived.length}`,
  '',
  "import type { CatalogItem } from './types.js';",
  '',
  'export const GENERATED_CATALOG: readonly CatalogItem[] = ',
  '',
].join('\n');

const body = `${JSON.stringify(derived, null, 2)} as const satisfies readonly CatalogItem[];\n`;

writeFileSync(outPath, banner + body);
console.info(`Wrote ${derived.length} entries to ${outPath}.`);
